import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// # Redux
import { Redux_Provider } from '@store/provider'

// React Query
import { ReactQuery_Provider } from "@utils/react-query/provider"

// React Toastify
import { ToastContainer } from 'react-toastify' ;
import 'react-toastify/dist/ReactToastify.css' ;

// # NextAuth
import AuthSession_Provider from '@/components/common/AuthSession_Provider'






const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {

  title       : 'Create Next App',
  description : 'Generated by create next app',

}



export default function RootLayout({ children } : { children: React.ReactNode }) {


  return (

            <AuthSession_Provider> 

                <html lang = "en" >

                    <body className = {inter.className} >

                          <Redux_Provider> 

                            <ToastContainer position              = "bottom-left"
                                                  autoClose       = { 5000  }
                                                  hideProgressBar = { false }
                                                  newestOnTop     = { false }
                                                  closeOnClick
                                                  rtl             = { false }
                                                  pauseOnFocusLoss
                                                  draggable
                                                  pauseOnHover />
                            
                              <ReactQuery_Provider> 

                                  { children }
              
                              </ReactQuery_Provider>

                          </Redux_Provider>

                    </body>

                </html>

            </AuthSession_Provider>
          
         )

}
